### ISSUE TITLE
[Issue] ASN: invalid ORG: AS

### ISSUE THREAD

**Issue by ehsandeep** [harleo/asnip#8]
```
asnip -t google.com
[?] ASN: invalid ORG: AS???
[:] Writing 0 CIDRs to file...
[:] Converting to IPs...
[:] Writing 0 IPs to file...
[!] Done.
```

Looks like an issue with hackertarget API?

**Comment by harleo** [comment]
Hello @ehsandeep, sorry for the late reply.

Seems to be working from my end with the latest version:
```
asnip -t google.com
[?] ASN: "15169" ORG: "GOOGLE, US"
[:] Writing 762 CIDRs to file...
[:] Converting to IPs...
[:] Writing 23035660 IPs to file...
[!] Done.
```

Could you recheck?

**Comment by ehsandeep** [comment]
@harleo still getting the same error:- 

```
date
Tue May  4 12:22:01 IST 2021

asnip -t google.com
[?] ASN: invalid ORG: AS???
[:] Writing 0 CIDRs to file...
[:] Converting to IPs...
[:] Writing 0 IPs to file...
[!] Done.
```

**Comment by harleo** [comment]
@ehsandeep Assuming you updated it before: `go get -u github.com/harleo/asnip`, what OS are you running it on? Maybe the rate limit parsing is not working properly, as you suggested initially. Have you tried running it from a different IP?

**Comment by ehsandeep** [comment]
```
go build asnip.go 
asnip $ls
LICENSE
README.md
asnip
asnip.go

./asnip -t google.com
[?] ASN: invalid ORG: AS???
[:] Writing 0 CIDRs to file...
[:] Converting to IPs...
[:] Writing 0 IPs to file...
[!] Done.
```

I'm using M1 
```
root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 arm64
```

**Comment by harleo** [comment]
@ehsandeep

That's weird, I don't have any other ideas. Maybe Intel/ARM issue?

> go build asnip.go
> ls
LICENSE   README.md asnip     asnip.go
> ./asnip -t google.com
```
[?] ASN: "15169" ORG: "GOOGLE, US"
[:] Writing 762 CIDRs to file...
[:] Converting to IPs...
[:] Writing 23035660 IPs to file...
[!] Done.
```
> uname -a
root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

**Comment by harleo** [comment]
@ehsandeep 
I haven't used ARM yet, I suppose the build process is different?

Can you try `env GOOS=linux GOARCH=arm GOARM=5 go build asnip.go` and see if that works?

**Comment by harleo** [comment]
@ehsandeep Have you figured this out?

**Comment by ehsandeep** [comment]
@harleo not sure what changed, but now it works, so closing the issue.

```console
asnip -t google.com
[?] ASN: "15169" ORG: "GOOGLE, US"
[:] Writing 748 CIDRs to file...
[:] Converting to IPs...
[:] Writing 22732584 IPs to file...
[!] Done.
```

Thank you.
